import matplotlib.pyplot as plt
import pandas as pd
import os
from scipy.interpolate import interp1d
import numpy as np

# read csv
dictYears = {}

# merge csv
for i in os.listdir(os.path.join(os.path.dirname(__file__), "../dataset/camera")):
    print(i)
    year = i.split("-")[1].split(".")[0]
    year = int(year[:4])
    dfCurr = pd.read_csv(os.path.join(os.path.dirname(
        __file__), "../dataset/camera/" + i), sep=";", encoding="latin-1") 
    dfCurr["year"] = year
    dfCurr = dfCurr[["year", "LISTA", "VOTI_LISTA"]]
    dfCurr["VOTI_LISTA"] = dfCurr["VOTI_LISTA"]
    dfCurr = dfCurr.groupby(["year", "LISTA"]).sum().reset_index()
    dfCurr["VOTANTI"] = dfCurr["VOTI_LISTA"].sum()
    dfCurr["PERCENTUALE"] = (dfCurr["VOTI_LISTA"] / dfCurr["VOTANTI"] * 100).round(2)
    dictYears[year] = dfCurr


print(dictYears)
df = pd.concat(dictYears.values(), ignore_index=True)
df = df.groupby(["year", "LISTA"]).sum().reset_index()
df = df.sort_values(by=["year", "VOTI_LISTA"], ascending=False)
df.to_csv(os.path.join(os.path.dirname(__file__),
          "../dataset/affluenze/merged.csv"), index=False)
print(df["LISTA"].unique())

centroDestra = ["FRATELLI D'ITALIA CON GIORGIA MELONI", "LEGA PER SALVINI PREMIER", "FORZA ITALIA",
                "ITALEXIT PER L'ITALIA", "LEGA", "CASAPOUND ITALIA", "FRATELLI D'ITALIA", "LEGA NORD", "ALLEANZA NAZIONALE", "LEGA LOMBARDA", "MSI-DN"]

centroSinistra = ["PARTITO DEMOCRATICO - ITALIA DEMOCRATICA E PROGRESSISTA", "MOVIMENTO 5 STELLE", "+EUROPA", "ALLEANZA VERDI E SINISTRA",
                  "PARTITO DEMOCRATICO", "LIBERI E UGUALI", "MOVIMENTO 5 STELLE BEPPEGRILLO.IT", "IL POPOLO DELLA LIBERTA'", "SINISTRA ECOLOGIA LIBERTA", "L'ULIVO",
                  "DEMOCRATICI SINISTRA",  "PDS", "P.POPOLARE ITALIANO", "PSI", "PCI", "FR.DEMOCR.POPOLARE"]

centroPuro = ["AZIONE - ITALIA VIVA - CALENDA",
              "SCELTA CIVICA CON MONTI PER L'ITALIA", "UNIONE DI CENTRO", "LA MARGHERITA", "DC"]



dictCheck = {}

for i in df["LISTA"].unique():
    print(i)

# listaPartiti = [
#                  'MOVIMENTO 5 STELLE BEPPEGRILLO.IT' "IL POPOLO DELLA LIBERTA'"
#                  "SCELTA CIVICA CON MONTI PER L'ITALIA" 'LEGA NORD'
#                  "SINISTRA ECOLOGIA LIBERTA'" 'RIVOLUZIONE CIVILE' "FRATELLI D'ITALIA"
#                  'UNIONE DI CENTRO' 'FARE PER FERMARE IL DECLINO' 'LA DESTRA'
#                  'CENTRO DEMOCRATICO' "FUTURO E LIBERTA'" 'GRANDE SUD - MPA' 'SVP'
#                  'PARTITO COMUNISTA DEI LAVORATORI' 'FORZA NUOVA'
#                  'MIR - MODERATI IN RIVOLUZIONE' "LISTA AMNISTIA GIUSTIZIA LIBERTA'"
#                  'PARTITO PENSIONATI' 'DIE FREIHEITLICHEN' 'FIAMMA TRICOLORE'
#                  "IO AMO L'ITALIA" 'INDIPENDENZA VENETA' "LIBERALI PER L'ITALIA - PLI"
#                  'INTESA POPOLARE' "PS D'AZ." 'LG.VENETA REPUBBLICA' 'VOTO DI PROTESTA'
#                  'VENETO STATO' 'RIFORMISTI ITALIANI' 'INDIPENDENZA PER LA SARDEGNA' 'PRI'
#                  'MERIS' 'PARTITO DI ALTERNATIVA COMUNISTA' 'I PIRATI'
#                  'MOVIMENTO PROGETTO ITALIA - MID' 'LIBERI PER UNA ITALIA EQUA'
#                  'RIFONDAZIONE MISSINA ITALIANA' 'POPOLARI UNITI' 'PROGETTO NAZIONALE'
#                  'MOVIMENTO P.P.A.' 'UNIONE POP.' "TUTTI INSIEME PER L'ITALIA"
#                  "STAMINALI D'ITALIA" 'DEMOCRAZIA ATEA' 'DI PIETRO ITALIA DEI VALORI'
#                  "LA SINISTRA L'ARCOBALENO" 'LA DESTRA - FIAMMA TRICOLORE'
#                  "MOVIMENTO PER L'AUTONOMIA ALL.PER IL SUD" 'PARTITO SOCIALISTA'
#                  'SINISTRA CRITICA' 'ASS.DIFESA DELLA VITA ABORTO?NO,GRAZIE'
#                  'PER IL BENE COMUNE' 'P.LIBERALE ITALIANO'
#                  'UNIONE DEMOCRATICA PER I CONSUMATORI' 'LISTA DEI GRILLI PARLANTI'
#                  'M.E.D.A.' "LEGA PER L'AUTONOMIA ALL.LOMB. LEGA PENS"
#                  'UNION FUR SUD TIROL' 'SARDIGNA NATZIONE' 'LEGA SUD' "L'INTESA VENETA"
#                  'IL LOTO' "L'ULIVO" 'ALLEANZA NAZIONALE' 'RIFONDAZIONE COMUNISTA'
#                  'LA ROSA NEL PUGNO' 'COMUNISTI ITALIANI' 'FEDERAZIONE DEI VERDI'
#                  'U.D.EUR POPOLARI' 'DEM.CRIST.-NUOVO PSI' 'ALTERNATIVA SOCIALE MUSSOLINI'
#                  'I SOCIALISTI ' 'PROGETTO NORDEST' 'LISTA CONSUMATORI' 'NO EURO'
#                  'ALLEANZA LOMBARDA AUTONOMIA' 'PENSIONATI UNITI' 'LIGA FRONTE VENETO'
#                  'AMBIENTA-LISTA' 'TERZO POLO' 'IRS' 'S.O.S. ITALIA' "SOLIDARIETA'"
#                  'MOV.DEM.SIC-NOI SIC.' 'PER IL SUD' 'MOVIMENTO TRIVENETO'
#                  'DIMENSIONE CHRISTIANA' 'DESTRA NAZIONALE' 'DEMOCRATICI SINISTRA'
#                  'LA MARGHERITA' 'LISTA DI PIETRO' 'CCD-CDU' 'DEMOCRAZIA EUROPEA'
#                  'PANNELLA-BONINO' 'IL GIRASOLE' 'NUOVO PSI' "PS D'AZ-SARD.NATZ."
#                  'PAESE NUOVO' 'ABOLIZIONE SCORPORO' "LEGA D'AZIONE MERIDIONALE"
#                  'FRONTE NAZIONALE' 'VERDI-VERDI' 'LISTA AMADU' 'REPUBBLICANI EUROPEI'
#                  'NOI SICILIANI' 'LIBERI E FORTI' 'SOCIAL.AUTON.'
#                  "MOVIMENTO DELLE LIBERTA'" 'LIBDEM.BASTA' 'COMUNISMO'
#                  'TERZO POLO AUTONOMIA' 'PDS' 'POP-SVP-PRI-UD-PRODI'
#                  'RINNOVAMENTO IT-DINI' 'PANNELLA-SGARBI' 'MOV.SOC.TRICOLORE' 'SOCIALISTA'
#                  'UNIONE NORD EST' 'MANI PULITE' 'NOI SICILIANI-FNS' "GR.INDIP.LIBERTA'"
#                  'AMBIENTALISTI' 'PART.UMANISTA' 'RINNOVAMENTO' "PATTO PER L'AGRO"
#                  'MOV.RIN.IT.' 'MOV.AUT.TOSCANO' 'PART.LEGGE NATURALE' 'NUOVA DEMOCRAZIA'
#                  'DEMOCRAZIA SOCIALE' 'FEDERALISTI LIBERALI' 'PER LE MARCHE'
#                  'NUOVE ENERGIE' "SVILUPPO-LEGALITA'" 'NORD LIBERO AUT.' 'PART.FEDERAL.'
#                  'RISORGIMENTO DEL SUD' 'P.POPOLARE ITALIANO' 'PATTO SEGNI'
#                  'LISTA PANNELLA' 'PSI' 'LA RETE-MOV.DEM.' 'ALLEANZA DEMOCRATICA'
#                  'SOCIALDEMOCRAZIA' 'PROGRAMMA ITALIA' 'LEGA ALPINA LUMBARDA'
#                  'LEGA AUT.VENETA' 'UN.POP.' 'SOLID.OCCUPAZ.SVILUP' 'PARTIDU INDIP.'
#                  'UNIONE DEM.ITALIANA' 'UN.CRIST.RIF.' "PATTO SOLIDARIETA'"
#                  'LG.ANGELA BOSSI' 'LEGA PER IL PIEMONTE' 'ALL.MERIDIONALE' 'ADA'
#                  'ALL.POP.' 'INIZIATIVA POP.DEM.' "L'ARCA" 'RIN.SALENTINA'
#                  'MOV.CRIST.DEM.' 'SOLID.PROGRESSO' 'INSIEME PER SVILUPPO'
#                  'LISTA FRANCO GRECO' 'RINASCITA SOCIALISTA' "DEM.E SOLIDARIETA'"
#                  'UNIONE MEDITERRANEA' 'MOV.MERIDIONALE' 'DEMOCRAZIA SICILIANA'
#                  'MOV.CATTOLICO DEM.' 'RIFORMISTI IRPINI' 'P.DEM.' "ALL.MUNICIPALITA'"
#                  'UTOPIA' 'MOV.REP.' 'MOV.CRIST.VERITAS' 'RIN.DEMOCRATICO'
#                  'LIBERAL DEM.EUROPEI' 'INSIEME PER CAMBIARE' 'P.POP.PROGRESSISTA'
#                  'MEDITERRANEO' 'MOV.LIBERALDEM.SOC.' 'ALL.PROGRAMMA' 'MOV.POP.CRIST.'
#                  'MOV.EUR.LIB.CRIST.' "IDEA CITTA'" 'AUTONOMIA SOCIALISTA'
#                  'ALL.PER I CASTELLI' 'CENTRO CRIST.DEM.' 'DEM.E RINNOVAMENTO' 'DC'
#                  'LEGA LOMBARDA' 'MSI-DN' 'PLI' 'PSDI' 'LISTA REFERENDUM' 'PPST' 'CPA'
#                  'FEDERALISMO-PENS.UV.' 'LA LEGA CAS-PENS.' 'LEGA ALPINA PIEMONT'
#                  'MOV.VEN.REG.AUT' 'UNION VENETO' 'VERDI FEDERALISTI' "L.VALLE D'AOSTA"
#                  'LG.LOMB.EUR.T.LIB.' 'GRUPPO DOLCHI-FOSSON' 'LEGA DELLE LEGHE'
#                  'PART.AMORE' 'PIEMONT LIBER' 'MOV.POL.DIF.AUTOMOB.' 'LEGA MARCHE'
#                  'LEGA LAZIO' 'E.ROMAGNA-LG PADANA' 'C.S.T.' 'P.CRIST.DEMOCRAZIA'
#                  "LEGA MERID.D'IT." 'PART.EUROPA 2000' 'VIVERE INSIEME'
#                  'PART.GIUSTIZIALISTA' 'MOV.EUR.AUTOMOB.' 'LG.NAZ.PROTESTA'
#                  'LG.MERID.UN.NAZ.' 'PCI' 'P.RAD' 'LISTA VERDE' 'DEM.PROL'
#                  'LIGA VENETA-PU' 'PIEMONT-AUT.REG.' 'PIEMONT' 'UV-ADP-PRI'
#                  'DC-PCI-PSI-PSDI' 'MOV.LIB.FISCALE' 'ALL.PENS.' 'P.VERDE I.VER.E.'
#                  'MOV.NAZ.IT.CACC.' 'PNI-CACCIA PESCA' 'MOV.FRIULI' 'PART.SUD.TIROL'
#                  'VERDI IT.-P.ECOL' 'ALL.UM.' 'NPP' 'GIUST. E LIB.' 'PART.NAZ.INQ.'
#                  'RINASCITA SIC.' 'MOV.IND.TLT' 'PART.NAZ.PENS.' 'LIGA VENETA'
#                  'LISTA PER TRIESTE' 'UV-UVP-D.POP.' 'PPTT' 'UN.DIF.PENS.' 'PART.MON.NAZ.'
#                  'UN.PEN.PENS.IT.' 'UNIONE SLOVENA' 'POE' 'LISTA DI LOTTA'
#                  'PART.CRIST.AZ.SOC.' 'VIV.LIB.' 'FR.NAZ.SIC.' 'MOV.ECOL.SARDO'
#                  'PLI-PRI-PSDI' 'NUOVA SINISTRA' 'PDUP' 'NUOVA SIN.UNITA' 'DN-CD'
#                  'UNIONE VALDOSTANA-DEMPROL-PLI' 'UNITA DELLA SINISTRA' 'DC-PSDI-PRI'
#                  'PARTITO POPOLARE ITALIANO' 'FRONTE GIUST.SIC.' 'PART.BEN.CIV.'
#                  'PART.POP.CALAB.' 'ASS.VAL.IND' 'FIORE MARGHERITA' 'PART.SIN.DEM.'
#                  'PCI-PSI-PDUP' 'DC-RV-UV-UVP-PRI' 'DEM.POP-UVP M.REG' 'TIROL.' 'MSI'
#                  'PSIUP' 'MANIFESTO' 'MOV.POL.LAV.' 'PC(MARX-LEN)IT' 'DC-UV-RV-PSDI'
#                  'DEM.POP.' 'PAPI' 'STELLA ROSSA-R.S.' 'AZ.CR.POP.' 'RINN.DEM.NAZ.'
#                  'PCS (MARX.-LEN.)' 'UN.FORZE DEM.' 'PART.AGRICOLTORI' 'FR.UOMO QUALUNQUE'
#                  'PSU' 'PDIUM' 'NUOVA REPUBBLICA' 'UV' 'MOV.SOC.' 'PST.PROG.SOC.'
#                  'UN.NAZ.SAL.PUB.' 'RAG.VOL."T"' 'PART.ORD.ECON.' 'PART.DEM.PROG.'
#                  'RAGGR.ITAL.' 'P.COM.RIVOL.' 'RIS.POP.' 'SACRO IDEAL.MONDO'
#                  'P.PROG.UNSIPO' 'PART.NAZ.MUT.COMB.IT' "CONC.UNITA'RURALE"
#                  'M.COMB.IT-FR.RIN.NAZ' 'MOV.POL.CATT.IT.' 'PART.SOC.CRIST.'
#                  'L.UNIT.SLOV.' 'MOV.COLT.E SAL.' 'RINN.SOC.' 'MOV.POP.IT.' 'AV.NAZ.'
#                  'PART.LAB.IT.' 'P.MONARCHICO POP.' 'P.NAZ.MONARCHICO' 'PRI-P.RAD.'
#                  "COMUNITA'" 'MOVIM.AUT.REG.-M.A.R.P.' 'P.CAT.RIS.NAZ.CPI'
#                  'FED.AUT.SOCIALDEM.IT' 'P.NAZIONALE LAVORO' 'AUT.PIEMONT-MOV.VIL.'
#                  'UNIONE TRIESTINA' "FR.DELL'INDIPENDENZA" 'MOV.PRO PENSIONATI'
#                  'FR.UNICO SOLDATO IT.' 'CONC.EUROPEA DEMOC.' 'MOV.INDIP.DIVORZISTI'
#                  'P.SOC.SICILIANO' 'MOV.NAZIONALE IT.' 'MOV.AZIONE-RINNOVAM.'
#                  'MOV.ECONOMICO IT.SOC' 'P.IT.MUT.INV.GUERRA' 'FR.DEMOCR.POPOLARE'
#                  "UNITA' SOCIALISTA" 'BLOCCO NAZIONALE' 'P.NAZ.MON.ALL.D.LAV.' 'PPST-PPTT'
#                  "P.CONTADINI D'ITALIA" 'PARTITO CRISTIANO SOCIALE' 'MOV.NAZ.DEM.SOC.'
#                  'UN.MOV.FEDERALISTI' 'BLOCCO POP.UNIONISTA' 'ALTRE LISTE'
#                  'PC.INTERNAZIONALISTA' 'FR.DEM.PROG.REPUB.' 'CONC.NAZ.COMBAT.UNIT'
#                  'P.DEMOLABURISTA IT.' 'P.INDIPENDENTE CONTADINI' 'P.DEM.IND.PENSIONATI'
#                  'AS.NAZ.CONG.DIS.GUER' "P.PATRIA E LIBERTA'" 'FR.DEGLI ITALIANI'
#                  'CONC.RUR.IND.AOSTA' 'GR.POL.LA DESTRA' 'FR.ANTIBOLSCEVICO IT'
#                  'UN.SOCIAL.INDIP.' 'RAGGRUP.POP.ITALIANO' 'MAGLIO' 'CONF.IT.LIBERI SIND.'
#                  "MOV.UNITA'D'IT." 'FR.UN.ANTICOM.RIS.N.' 'M.NAZ.SIN.DAN.GUERRA'
#                  'LEGA SARDA' 'M.CAT.IND.PAX JUSTIT' 'P.ESISTENZIALISTA IT']
